pkgs: version: hpkgs: with hpkgs;

# These work with every version of GHC environments are created for
[
  QuickCheck_2_12_6_1
  aeson_1_4_2_0
  aeson-casing
  amazonka
  amazonka-core
  amazonka-cost-explorer
  amazonka-s3
  amazonka-pricing
  amqp
  async
  base
  base-orphans_0_8
  base-encoding
  base64-bytestring
  bytestring
  conduit
  conduit-extra
  containers
  contravariant
  criterion_1_5_3_0
  cron
  cryptonite
  cryptonite-conduit
  digest
  fast-logger
  generics-sop_0_4_0_1
  ghc
  hedgehog
  hspec_2_6_0
  hspec-core_2_6_0
  hspec-discover_2_6_0
  hspec-wai
  hspec-wai-json
  http-api-data_0_4
  http-client
  http-client-tls
  json
  lens
  machines
  miso
  mtl
  monad-logger
  network_2_8_0_0
  persistent
  persistent-mysql
  persistent-template
  pipes
  pipes-concurrency
  pipes-csv
  pipes-group
  pipes-parse
  semigroupoids_5_3_1
  servant_0_15
  servant-client_0_15
  servant-client-core_0_15
  servant-server_0_15
  tagged_0_8_6
  tasty
  tasty-hunit
  tasty-quickcheck
  tasty-th
  template-haskell
  text
  time
  transformers
  unordered-containers
  uuid
  vector
  wai
  wai-logger
  warp
  xml
]
